//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPFCONF.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class upfconEntities : DbContext
    {
        public upfconEntities()
            : base("name=upfconEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Administrateur> Administrateurs { get; set; }
        public virtual DbSet<Comite> Comites { get; set; }
        public virtual DbSet<Congre> Congres { get; set; }
        public virtual DbSet<Participant> Participants { get; set; }
        public virtual DbSet<Participation> Participations { get; set; }
        public virtual DbSet<Presentation> Presentations { get; set; }
        public virtual DbSet<Session> Sessions { get; set; }
        public virtual DbSet<Autorisation_Admin> Autorisation_Admin { get; set; }
    }
}
