//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPFCONF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comite
    {
        public int ID_Comite { get; set; }
        public int ID_Congres { get; set; }
        public string Nom_Comite { get; set; }
        public string President { get; set; }
    
        public virtual Congre Congre { get; set; }
    }
}
