//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPFCONF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Participation
    {
        public int ID_Participation { get; set; }
        public int ID_Participant { get; set; }
        public int ID_Session { get; set; }
        public System.DateTime Date_Participation { get; set; }
    
        public virtual Participant Participant { get; set; }
        public virtual Session Session { get; set; }
    }
}
