//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPFCONF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Presentation
    {
        public int ID_Presentation { get; set; }
        public int ID_Session { get; set; }
        public string Nom_Conferencier { get; set; }
        public string Sujet { get; set; }
    
        public virtual Session Session { get; set; }
    }
}
